import * as fs from 'fs'

async function main() {
  console.log('Fetching MA POTW data from EPA ECHO...')

  const res = await fetch(
    'https://echodata.epa.gov/echo/cwa_rest_services.get_facility_info?output=JSON&p_st=MA&p_fac_typ=POTW&p_act=Y&responseset=500'
  )
  const text = await res.text()
  console.log('Raw response preview:', text.slice(0, 500))
  const data = JSON.parse(text) as any

  const facilities = data?.Results?.Facilities ?? []
  console.log(`Found ${facilities.length} MA POTW facilities`)

  const lookup: Record<string, {
    name: string
    designFlowMGD: number | null
    actualFlowMGD: number | null
    permitStatus: string | null
    city: string | null
  }> = {}

  for (const f of facilities) {
    const id = f.SourceID
    if (!id) continue
    lookup[id] = {
      name: f.CWPName ?? null,
      designFlowMGD: f.CWPDesignFlowNmbr ? parseFloat(f.CWPDesignFlowNmbr) : null,
      actualFlowMGD: f.CWPActualAverageFlowNmbr ? parseFloat(f.CWPActualAverageFlowNmbr) : null,
      permitStatus: f.CWPPermitStatusDesc ?? null,
      city: f.CWPCity ?? null,
    }
  }

  const output = `// Auto-generated by scripts/fetch-potw-data.ts
// Last updated: ${new Date().toISOString().split('T')[0]}
// Source: EPA ECHO CWA REST Services

export interface POTWRecord {
  name: string
  designFlowMGD: number | null
  actualFlowMGD: number | null
  permitStatus: string | null
  city: string | null
}

export const MA_POTW_LOOKUP: Record<string, POTWRecord> = ${JSON.stringify(lookup, null, 2)}
`

  fs.writeFileSync('src/data/ma-potw-lookup.ts', output)
  console.log(`Written to src/data/ma-potw-lookup.ts with ${Object.keys(lookup).length} records`)
}

main().catch(console.error)
