import * as fs from 'fs'

async function main() {
  console.log('Step 1: Getting QID from ECHO...')

  // Step 1: get_facilities returns a QID
  const step1 = await fetch(
    'https://echodata.epa.gov/echo/cwa_rest_services.get_facilities?output=JSON&p_st=MA&p_fac_typ=POTW&p_act=Y&p_limit_addr=N'
  )
  const step1data = await step1.json() as any
  const qid = step1data?.Results?.QueryID
  const total = step1data?.Results?.QueryRows
  console.log(`QID: ${qid}, Total rows: ${total}`)

  if (!qid) {
    console.error('No QID returned:', JSON.stringify(step1data).slice(0, 500))
    return
  }

  // Step 2: paginate through results using get_qid
  const allFacilities: any[] = []
  let page = 1
  const pageSize = 100

  while (true) {
    console.log(`Fetching page ${page}...`)
    const res = await fetch(
      `https://echodata.epa.gov/echo/cwa_rest_services.get_qid?output=JSON&qid=${qid}&pageno=${page}&responseset=${pageSize}`
    )
    const data = await res.json() as any
    const facilities = data?.Results?.Facilities ?? []
    if (facilities.length === 0) break
    allFacilities.push(...facilities)
    console.log(`  Got ${facilities.length} facilities (total so far: ${allFacilities.length})`)
    if (facilities.length < pageSize) break
    page++
    // small delay to be polite to the API
    await new Promise(r => setTimeout(r, 200))
  }

  console.log(`Total facilities fetched: ${allFacilities.length}`)

  const lookup: Record<string, {
    name: string
    designFlowMGD: number | null
    actualFlowMGD: number | null
    permitStatus: string | null
    city: string | null
  }> = {}

  for (const f of allFacilities) {
    const id = f.SourceID
    if (!id) continue
    lookup[id] = {
      name: f.CWPName ?? null,
      designFlowMGD: f.CWPDesignFlowNmbr ? parseFloat(f.CWPDesignFlowNmbr) : null,
      actualFlowMGD: f.CWPActualAverageFlowNmbr ? parseFloat(f.CWPActualAverageFlowNmbr) : null,
      permitStatus: f.CWPPermitStatusDesc ?? null,
      city: f.CWPCity ?? null,
    }
  }

  const output = `// Auto-generated by scripts/fetch-potw-data.ts
// Last updated: ${new Date().toISOString().split('T')[0]}
// Source: EPA ECHO CWA REST Services — MA POTWs

export interface POTWRecord {
  name: string
  designFlowMGD: number | null
  actualFlowMGD: number | null
  permitStatus: string | null
  city: string | null
}

export const MA_POTW_LOOKUP: Record<string, POTWRecord> = ${JSON.stringify(lookup, null, 2)}
`

  fs.writeFileSync('src/data/ma-potw-lookup.ts', output)
  console.log(`Written ${Object.keys(lookup).length} records to src/data/ma-potw-lookup.ts`)
}

main().catch(console.error)
