/**
 * Parse 2024 building permit data from UMass Donahue Institute Excel file
 * and generate a static TypeScript data module.
 *
 * Usage: npx tsx scripts/parse-building-permits.ts
 * Output: src/data/building_permits_2024.ts
 */

import * as XLSX from 'xlsx'
import * as fs from 'fs'
import * as path from 'path'

// Read existing town data to build slug lookup
const townDataPath = path.join(__dirname, '../src/data/town_seo_data.ts')
const townDataContent = fs.readFileSync(townDataPath, 'utf-8')

// Extract slug/name pairs from the TS source (simple regex approach)
const townEntries: { slug: string; name: string }[] = []
const re = /slug:\s*'([^']+)',\s*name:\s*'([^']+)'/g
let match
while ((match = re.exec(townDataContent)) !== null) {
  townEntries.push({ slug: match[1], name: match[2] })
}

// Build name -> slug lookup (lowercase name as key)
const nameToSlug = new Map<string, string>()
for (const t of townEntries) {
  nameToSlug.set(t.name.toLowerCase(), t.slug)
}

// Known name mismatches between Census data and our town data
const NAME_OVERRIDES: Record<string, string> = {
  'manchester-by-the-sea': 'manchester-by-the-sea',
  'manchester': 'manchester-by-the-sea',
}

// Read Excel file
const xlsxPath = path.join(__dirname, '../data/Building_permits_2000_2024.xlsx')
const wb = XLSX.readFile(xlsxPath)

const sheetName = 'Mass2024Annl-all 351 by county'
const ws = wb.Sheets[sheetName]
if (!ws) {
  console.error(`Sheet "${sheetName}" not found. Available sheets:`, wb.SheetNames)
  process.exit(1)
}

const raw: (string | number | null | undefined)[][] = XLSX.utils.sheet_to_json(ws, { header: 1 })

interface ParsedRow {
  slug: string
  name: string
  totalUnits: number
  singleFamilyUnits: number
  multifamilyUnits: number
}

const results: ParsedRow[] = []
const unmatchedExcel: string[] = []

// Data starts at row index 5 (0=title, 1=subheader, 2=colheaders, 3=blank, 4=state agg)
for (let i = 5; i < raw.length; i++) {
  const row = raw[i]
  if (!row || row.length < 25) continue

  // Column index 2 (0-indexed) = 6-Digit ID. County/state rows have no ID.
  const sixDigitId = row[2]
  if (!sixDigitId) continue

  // Area Name is at column index 13
  let areaName = String(row[13] || '').trim()
  if (!areaName) continue

  // Skip if this is "Massachusetts" (state aggregate repeated at bottom)
  if (areaName.toLowerCase() === 'massachusetts') continue

  // Strip " town" / " Town" suffix
  areaName = areaName.replace(/\s+[Tt]own$/, '')

  // Extract imputed unit counts
  const sfUnits = Number(row[15]) || 0
  const twoFamUnits = Number(row[18]) || 0
  const threeFourFamUnits = Number(row[21]) || 0
  const fivePlusUnits = Number(row[24]) || 0

  const totalUnits = sfUnits + twoFamUnits + threeFourFamUnits + fivePlusUnits
  const multifamilyUnits = twoFamUnits + threeFourFamUnits + fivePlusUnits

  // Match to existing slug
  const nameLower = areaName.toLowerCase()
  const slugFromName = nameLower.replace(/\s+/g, '-')
  let slug = nameToSlug.get(nameLower) || NAME_OVERRIDES[slugFromName] || null

  if (!slug) {
    // Try slug-based lookup
    slug = townEntries.find(t => t.slug === slugFromName)?.slug || null
  }

  if (!slug) {
    unmatchedExcel.push(areaName)
    slug = slugFromName // Use generated slug as fallback
  }

  results.push({
    slug,
    name: areaName,
    totalUnits,
    singleFamilyUnits: sfUnits,
    multifamilyUnits,
  })
}

// Sort alphabetically by slug
results.sort((a, b) => a.slug.localeCompare(b.slug))

// Report unmatched
if (unmatchedExcel.length > 0) {
  console.error(`\n--- ${unmatchedExcel.length} Excel names not matched to existing town data ---`)
  unmatchedExcel.forEach(n => console.error(`  ${n}`))
}

// Find towns in our data that have no building permit match
const resultSlugs = new Set(results.map(r => r.slug))
const unmatchedTowns = townEntries.filter(t => !resultSlugs.has(t.slug))
if (unmatchedTowns.length > 0) {
  console.error(`\n--- ${unmatchedTowns.length} towns in town_seo_data not found in Excel ---`)
  unmatchedTowns.forEach(t => console.error(`  ${t.name} (${t.slug})`))
}

console.error(`\nParsed ${results.length} municipalities from 2024 building permit data`)

// Generate TypeScript output
const lines: string[] = []
lines.push(`// GENERATED by scripts/parse-building-permits.ts — do not edit manually`)
lines.push(`// Source: U.S. Census Bureau Annual Building Permit Survey (2024) via UMass Donahue Institute`)
lines.push(`// Uses imputed columns (reported + estimated for non-reporters)`)
lines.push(``)
lines.push(`export interface BuildingPermitData {`)
lines.push(`  slug: string`)
lines.push(`  name: string`)
lines.push(`  totalUnits: number`)
lines.push(`  singleFamilyUnits: number`)
lines.push(`  multifamilyUnits: number`)
lines.push(`}`)
lines.push(``)
lines.push(`const buildingPermits2024: BuildingPermitData[] = [`)

for (const r of results) {
  lines.push(`  { slug: '${r.slug}', name: '${r.name.replace(/'/g, "\\'")}', totalUnits: ${r.totalUnits}, singleFamilyUnits: ${r.singleFamilyUnits}, multifamilyUnits: ${r.multifamilyUnits} },`)
}

lines.push(`]`)
lines.push(``)
lines.push(`export default buildingPermits2024`)
lines.push(``)
lines.push(`export function getBuildingPermitsBySlug(slug: string): BuildingPermitData | undefined {`)
lines.push(`  return buildingPermits2024.find(t => t.slug === slug)`)
lines.push(`}`)
lines.push(``)
lines.push(`export const buildingPermitMap = new Map(buildingPermits2024.map(t => [t.slug, t]))`)
lines.push(``)

const outputPath = path.join(__dirname, '../src/data/building_permits_2024.ts')
fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8')
console.log(`\nWrote ${results.length} entries to ${outputPath}`)
