// infrastructure-data.ts
// Board of Health Septic Regulation Analysis — local rules measured against Title 5 baseline (310 CMR 15.000)
// Local Boards of Health are authorized under M.G.L. c. 111, § 31 to adopt regulations stricter than Title 5.
// Exceeding the state baseline is not a legal deficiency — it is an exercise of granted local authority.

export type InfrastructureStatus =
  | 'exceeds_baseline'  // Local rule stricter than Title 5
  | 'barrier'           // Structural block (e.g., no variance relief for ADUs)
  | 'needs_review'      // Ambiguous or unconfirmed
  | 'consistent';       // Matches or is less strict than Title 5

export type ImpactLevel = 'critical' | 'high' | 'moderate' | 'neutral';

export const statusConfig: Record<
  InfrastructureStatus,
  { label: string; color: string; bg: string; border: string; dot: string }
> = {
  exceeds_baseline: {
    label: 'Exceeds Baseline',
    color: 'text-orange-400',
    bg: 'bg-orange-400/10',
    border: 'border-orange-400/30',
    dot: 'bg-orange-400',
  },
  barrier: {
    label: 'Barrier',
    color: 'text-red-400',
    bg: 'bg-red-400/10',
    border: 'border-red-400/30',
    dot: 'bg-red-400',
  },
  needs_review: {
    label: 'Needs Review',
    color: 'text-amber-400',
    bg: 'bg-amber-400/10',
    border: 'border-amber-400/30',
    dot: 'bg-amber-400',
  },
  consistent: {
    label: 'Consistent',
    color: 'text-emerald-400',
    bg: 'bg-emerald-400/10',
    border: 'border-emerald-400/30',
    dot: 'bg-emerald-400',
  },
};

export const impactConfig: Record<
  ImpactLevel,
  { label: string; color: string; bg: string }
> = {
  critical: { label: 'Critical Impact', color: 'text-red-400', bg: 'bg-red-400/10' },
  high: { label: 'High Impact', color: 'text-orange-400', bg: 'bg-orange-400/10' },
  moderate: { label: 'Moderate Impact', color: 'text-amber-400', bg: 'bg-amber-400/10' },
  neutral: { label: 'Neutral', color: 'text-gray-400', bg: 'bg-gray-700/30' },
};

export interface InfrastructureProvision {
  id: string;
  title: string;
  status: InfrastructureStatus;
  impact: ImpactLevel;
  localRule: string;
  stateBaseline: string;
  gap: string;
  localRegulation: string;
  stateCitation: string;
  details: string;
  sourcingNote?: string;
}

export interface InfrastructureTown {
  slug: string;
  name: string;
  county: string;
  regulatoryLayer: string;
  stateBaseline: string;
  localAuthority: string;
  lastReviewed: string;
  bottomLine: string;
  provisions: InfrastructureProvision[];
  sources: {
    label: string;
    url: string;
  }[];
}

export function getStatusCounts(provisions: InfrastructureProvision[]) {
  return {
    exceeds: provisions.filter(p => p.status === 'exceeds_baseline').length,
    barrier: provisions.filter(p => p.status === 'barrier').length,
    review: provisions.filter(p => p.status === 'needs_review').length,
    consistent: provisions.filter(p => p.status === 'consistent').length,
  };
}

export function getTownStatusLabel(town: InfrastructureTown) {
  const counts = getStatusCounts(town.provisions);
  if (counts.barrier > 0) return statusConfig.barrier;
  if (counts.exceeds > 0) return statusConfig.exceeds_baseline;
  if (counts.review > 0) return statusConfig.needs_review;
  return statusConfig.consistent;
}

export const infrastructureTowns: InfrastructureTown[] = [
  {
    slug: 'duxbury',
    name: 'Duxbury',
    county: 'Plymouth County',
    regulatoryLayer: 'Board of Health Supplementary Rules & Regulations to Title 5',
    stateBaseline: '310 CMR 15.000 (Title 5 of the State Environmental Code)',
    localAuthority: 'M.G.L. c. 111, § 31',
    lastReviewed: '2026-03-03',
    bottomLine: "Massachusetts law (M.G.L. c. 111, § 31) authorizes local Boards of Health to adopt septic regulations stricter than the state Title 5 baseline. Duxbury has exercised that authority \u2014 its supplementary rules exceed Title 5 minimums in at least four areas relevant to ADU construction: groundwater separation, wetland setbacks, private well setbacks, and irrigation well setbacks. These stricter standards are legally authorized and reflect local environmental and public health priorities. However, because ADUs are treated as new construction, variance relief is not available \u2014 unlike virtually every other septic project that comes before the Board. A homeowner may have the right to build an ADU under state zoning law, but their lot may not support a septic system under the town\u2019s Board of Health rules. A critical open question is whether Duxbury accepts bedroom reallocation \u2014 reducing the main house bedroom count to allocate septic capacity to the ADU \u2014 as a feasibility pathway. This practice is becoming standard in other Massachusetts towns but has not been publicly confirmed in Duxbury.",
    provisions: [
      {
        id: 'DUX-T5-01',
        title: 'Groundwater Separation',
        status: 'exceeds_baseline',
        impact: 'high',
        localRule: '6 ft above max high groundwater in fast-perc soils (\u22642 min/inch)',
        stateBaseline: '5 ft above high groundwater in fast-perc soils; 4 ft in slower soils',
        gap: '+1 foot above state minimum',
        localRegulation: 'Section 1.11.1B',
        stateCitation: '310 CMR 15.212(1)(b)',
        details: "Duxbury requires an additional foot of vertical separation between the soil absorption system and high groundwater in fast-percolating soils. BoH meeting minutes show variance requests for this provision are routine \u2014 December 2024 alone included multiple properties requesting 6\u21925 ft relief. However, ADUs as new construction cannot receive variance relief per town counsel guidance (March 2025 BoH meeting).",
      },
      {
        id: 'DUX-T5-02',
        title: 'Wetland Setback',
        status: 'exceeds_baseline',
        impact: 'critical',
        localRule: '150 ft from bordering vegetated wetlands',
        stateBaseline: '50 ft from bordering vegetated wetlands',
        gap: '3\u00d7 the state minimum (+100 ft)',
        localRegulation: 'Section 1.101A',
        stateCitation: '310 CMR 15.211',
        details: "Duxbury\u2019s 150-foot wetland buffer consumes a significant portion of buildable area on many lots. December 2025 BoH meeting minutes record a variance granted reducing the wetland setback from 150 ft to 54 ft \u2014 nearly back to the state floor \u2014 because there was no feasible alternative location. This type of relief is not available for ADU projects.",
      },
      {
        id: 'DUX-T5-03',
        title: 'Private Well Setback',
        status: 'exceeds_baseline',
        impact: 'high',
        localRule: '150 ft from private drinking water wells',
        stateBaseline: '100 ft (reducible to 50 ft with water quality testing)',
        gap: '+50 ft above state minimum',
        localRegulation: 'Section 2.0',
        stateCitation: '310 CMR 15.211',
        details: "Duxbury has a significant number of homes on private wells. The 150-ft well setback radius, combined with the 150-ft wetland buffer, can leave zero viable area for a new septic system on smaller lots. Title 5 allows further reduction to 50 ft with water quality testing; Duxbury\u2019s regulations do not provide the same flexibility.",
      },
      {
        id: 'DUX-T5-04',
        title: 'Irrigation Well Setback',
        status: 'exceeds_baseline',
        impact: 'moderate',
        localRule: '100 ft from irrigation wells',
        stateBaseline: '25 ft from irrigation wells',
        gap: '4\u00d7 the state minimum (+75 ft)',
        localRegulation: 'Section 2.06.3G',
        stateCitation: '310 CMR 15.211',
        details: "Where irrigation wells exist on a property, the 100-ft radius reduces the area available for a new septic leaching field. August 2025 BoH meeting minutes include discussion in which a board member acknowledged the 100-ft requirement may have been set without strong technical justification.",
      },
      {
        id: 'DUX-T5-05',
        title: 'No Variance Relief for ADUs',
        status: 'barrier',
        impact: 'critical',
        localRule: 'ADUs = new construction; must meet all local standards without variances',
        stateBaseline: 'No specific ADU septic provision in Title 5',
        gap: 'Variance pathway unavailable for ADU projects',
        localRegulation: 'Town Counsel Guidance (March 2025)',
        stateCitation: '310 CMR 15.000',
        details: "Town counsel confirmed that Duxbury\u2019s supplementary rules apply to ADUs and that because ADUs are new construction, they must meet all local standards without variances. Existing homeowners routinely receive variance approvals for setback and groundwater provisions. ADU projects cannot access the same relief pathway.",
        sourcingNote: "This guidance comes from town counsel\u2019s statements during the March 20, 2025 BoH meeting as recorded in meeting minutes, not from a codified regulation. The Board of Health could potentially evaluate ADU variance requests on a case-by-case basis.",
      },
      {
        id: 'DUX-T5-06',
        title: 'Bedroom Definition',
        status: 'consistent',
        impact: 'neutral',
        localRule: 'Any room providing privacy with at least one window = bedroom for flow calculation',
        stateBaseline: 'Room providing privacy, intended primarily for sleeping',
        gap: 'None identified',
        localRegulation: 'Septic System Requirements',
        stateCitation: '310 CMR 15.002',
        details: "Duxbury\u2019s bedroom definition appears consistent with the Title 5 definition. A 1-bedroom ADU = 110 gpd design flow. If an ADU contains a room qualifying as a second bedroom, design flow increases accordingly.",
      },
      {
        id: 'DUX-T5-07',
        title: 'Bedroom Reallocation Policy',
        status: 'needs_review',
        impact: 'critical',
        localRule: "Not explicitly addressed in Duxbury BoH supplementary rules. Town allows ADU connection to existing septic if system has adequate capacity and passes Title 5 inspection. Bedroom reallocation (reducing main house bedroom count to allocate to ADU) has not been explicitly confirmed or denied as an accepted pathway.",
        stateBaseline: "Title 5 (310 CMR 15.000) calculates septic capacity based on total bedroom count on a lot. No state-level provision specifically addresses bedroom reallocation between a principal dwelling and an ADU. EOHLC has not issued guidance on this practice.",
        gap: "No explicit local policy \u2014 standard practice emerging statewide but not codified in Duxbury",
        localRegulation: 'No specific regulation identified',
        stateCitation: '310 CMR 15.002 (bedroom definition), 310 CMR 15.203 (design flow)',
        details: "Bedroom reallocation \u2014 reducing the main house bedroom count and allocating that capacity to the ADU \u2014 is emerging as the primary feasibility pathway for ADU construction on septic-constrained lots across Massachusetts. Builders report that for lots where septic expansion is impossible due to water protection overlays, high groundwater, or wetland setbacks (see DUX-T5-01 through DUX-T5-04), reallocation is often the only viable option. The process typically involves removing a closet and widening a doorway to 48 inches so the room no longer qualifies as a bedroom under building code, then tying the ADU into the existing septic system. However, whether Duxbury\u2019s Board of Health and building inspector accept this approach has not been publicly confirmed. Given that DUX-T5-05 indicates ADUs are treated as new construction without variance relief, the question of whether bedroom reallocation is treated as a septic modification (requiring BoH review) or simply a building code change (handled by the building inspector) is unresolved.",
        sourcingNote: "This provision is based on builder interviews and cross-town pattern analysis, not Duxbury-specific BoH documentation. Builders active in Sharon, Mansfield, and other towns confirm bedroom reallocation is accepted practice in those communities. Duxbury\u2019s specific position has not been confirmed through BoH meeting minutes or published guidance. Verification with Duxbury\u2019s BoH and building inspector is recommended before relying on this pathway for a specific project.",
      },
    ],
    sources: [
      { label: 'Duxbury BoH \u2014 Septic System Requirements', url: 'https://www.town.duxbury.ma.us/board-health/pages/septic-system-requirements' },
      { label: 'Duxbury BoH \u2014 Private Wells', url: 'https://www.town.duxbury.ma.us/board-health/pages/private-wells' },
      { label: 'Duxbury BoH \u2014 Local & State Regulations', url: 'https://www.town.duxbury.ma.us/board-health/pages/local-state-regulations' },
      { label: 'Duxbury BoH \u2014 Title 5 vs. Duxbury Rules FAQ', url: 'https://www.town.duxbury.ma.us/board-health/faq/what-difference-between-title-5-and-duxbury-rules-regulations' },
      { label: 'BoH Meeting Minutes, March 20, 2025', url: 'https://duxbury.substack.com/p/duxbury-board-of-health-march-20' },
      { label: 'BoH Meeting Minutes, August 14, 2025', url: 'https://duxbury.substack.com/p/duxbury-board-of-health-august-14' },
      { label: 'BoH Meeting Minutes, December 4, 2024', url: 'https://duxbury.substack.com/p/duxbury-board-of-health-december' },
      { label: 'BoH Meeting Minutes, December 18, 2025', url: 'https://duxbury.substack.com/p/duxbury-board-of-health-december-d8c' },
      { label: '310 CMR 15.211 \u2014 Minimum Setback Distances', url: 'https://www.law.cornell.edu/regulations/massachusetts/310-CMR-15-211' },
      { label: '310 CMR 15.212 \u2014 Depth to Groundwater', url: 'https://www.law.cornell.edu/regulations/massachusetts/310-CMR-15-212' },
    ],
  },
  {
    slug: 'falmouth',
    name: 'Falmouth',
    county: 'Barnstable County',
    regulatoryLayer: 'Falmouth Health Regulations FHR-15.0 and FHR-15.15',
    stateBaseline: '310 CMR 15.000 (Title 5 of the State Environmental Code)',
    localAuthority: 'M.G.L. c. 111, § 31; M.G.L. c. 21A, § 13',
    lastReviewed: '2026-03-07',
    bottomLine: "Falmouth's Board of Health supplements stack three independent constraints on ADU septic projects. First, all leaching facilities serving new construction must be 100 feet from surface water or wetlands — double the Title 5 baseline of 50 feet — and ADUs as new construction cannot access the graduated repair pathway that permits closer placement with enhanced engineering. Second, FHR 15.15 (Version 10.6, August 2025) requires Best Available Nitrogen Reducing Technology — an I/A system achieving ≤10 mg/L total nitrogen — for all new construction on any lot any part of which is in a Nitrogen Sensitive Area. That requirement explicitly includes flow increases to existing systems, meaning an ADU addition that adds even one bedroom triggers mandatory I/A. Third, 16 of Falmouth's 19 watersheds are designated NSAs, covering 86% of the town's ponds and the vast majority of developed residential land. A separate DEP watershed permitting process requires all homes in affected watersheds to upgrade to the same BANRT standard by approximately 2030 if watershed permits are not obtained — meaning ADU builders may be front-running a cost that arrives anyway. The bedroom reallocation question is material: if reallocation avoids triggering a flow increase, the ADU may not qualify as new construction under FHR 15.15's explicit definition, potentially avoiding the I/A requirement.",
    provisions: [
      {
        id: 'FAL-T5-01',
        title: 'Wetland / Surface Water Setback (New Construction)',
        status: 'exceeds_baseline',
        impact: 'critical',
        localRule: '100 ft from surface water or wetlands for any leaching facility serving new construction. Sealed septic tank held to 50 ft.',
        stateBaseline: '50 ft from bordering vegetated wetland or surface water',
        gap: '2× the state minimum (+50 ft)',
        localRegulation: 'FHR 15.6(1)',
        stateCitation: '310 CMR 15.211',
        details: 'FHR 15.6(1) is an absolute prohibition — no leaching facility for new construction within 100 ft of surface water or wetlands as defined under both 310 CMR 15.002 and the Wetlands Protection Act (310 CMR 10.00). ADUs are new construction; this setback applies in full. Coastal and pond-adjacent lots common throughout Falmouth are directly affected.',
      },
      {
        id: 'FAL-T5-02',
        title: 'No Repair-Pathway Relief for ADUs',
        status: 'barrier',
        impact: 'critical',
        localRule: 'Graduated repair conditions (FHR 15.6(2)) permitting leaching at 40–100 ft from wetlands with enhanced engineering apply only to repairs of existing systems, not new construction.',
        stateBaseline: 'Variance and repair pathways available for systems approaching resource areas',
        gap: 'ADUs as new construction cannot access tiered engineering alternatives that would otherwise permit closer placement',
        localRegulation: 'FHR 15.6(2)',
        stateCitation: '310 CMR 15.000',
        details: 'The repair pathway creates a practical escape valve under Title 5 for systems that cannot achieve 50 ft. Falmouth\'s structure denies ADU projects that escape valve entirely. An open question for attorney review: if an ADU is connected to an existing system and characterized as a flow increase rather than new construction (a system upgrade rather than new construction), does it shift into the repair pathway? This classification question is material and unresolved in the regulation text.',
        sourcingNote: 'The new construction vs. repair classification for ADU additions is an open legal question. Attorney review recommended before relying on either characterization for a specific project.',
      },
      {
        id: 'FAL-T5-03',
        title: 'Graduated Repair Engineering Requirements',
        status: 'exceeds_baseline',
        impact: 'high',
        localRule: 'For repairs at 40–100 ft from wetlands: standard conditions at 50–100 ft with adequate groundwater separation; pressure distribution required at 50–75 ft with lower GW separation; alternative system + disinfection + pressure distribution required at 40–50 ft with lower GW separation.',
        stateBaseline: 'Standard repair variance process',
        gap: 'Significant cost and design complexity added for repairs near resource areas',
        localRegulation: 'FHR 15.6(2)(a)–(e)',
        stateCitation: '310 CMR 15.000',
        details: 'Even if an ADU project accesses the repair pathway, it faces escalating engineering requirements depending on proximity to the wetland and seasonal high groundwater depth. At 40–50 ft with shallow groundwater, an alternative system with disinfection unit plus pressure distribution is mandatory — a substantial cost add relative to a standard system.',
      },
      {
        id: 'FAL-T5-04',
        title: 'Mandatory I/A Technology — Nitrogen Sensitive Areas',
        status: 'exceeds_baseline',
        impact: 'critical',
        localRule: 'FHR 15.15: All new construction on any lot any part of which is in a Nitrogen Sensitive Area must incorporate Best Available Nitrogen Reducing Technology — an I/A system achieving ≤10 mg/L total nitrogen for the lifetime of the system. "New construction" explicitly includes any increase in actual or design flow to any system.',
        stateBaseline: 'I/A technology not required for new construction; nitrogen loading limit of 440 gpd/acre in sensitive areas',
        gap: 'Mandatory advanced treatment technology for all NSA new construction; ≤10 mg/L TN performance threshold exceeds what many standard I/A systems achieve',
        localRegulation: 'FHR 15.15 (Version 10.6, August 2025)',
        stateCitation: '310 CMR 15.215; 314 CMR 21.00',
        details: 'Three elements make this provision particularly significant for ADU analysis. First, the new construction definition explicitly includes flow increases — an ADU that adds even one bedroom triggers the requirement. Second, the NSA trigger is lot-based: if any part of the lot is in an NSA, the entire project is subject. Third, the ≤10 mg/L TN threshold is a demanding performance standard — systems achieving it (Fuji Clean, Advantex AX-Max, BioClear) carry higher equipment and installation costs, typically $20,000–$40,000 above a conventional system plus annual service contracts. Exception: new construction in a future sewer service area is exempt if Town Meeting has appropriated design funding and voters have approved the ballot measure at permit issuance.',
        sourcingNote: 'FHR 15.15 is labeled Version 10.6 dated August 6, 2025. Confirm official adoption and effective date directly with Falmouth Health Department.',
      },
      {
        id: 'FAL-T5-05',
        title: 'NSA Geographic Coverage',
        status: 'exceeds_baseline',
        impact: 'high',
        localRule: '16 of 19 Falmouth watersheds are designated Nitrogen Sensitive Areas. 67 of 78 town ponds (86%) intersect with an NSA. Non-NSA watersheds: Herring Brook (B5), Great Sippewisset Creek (B7), Little Sippewisset Marsh (B8), Direct Discharge areas (B9, S3), Salt Pond (S2).',
        stateBaseline: 'No statewide NSA designation system equivalent',
        gap: 'Near-universal NSA coverage of developed residential land in Falmouth',
        localRegulation: 'FHR 15.15; DEP Watershed Permit Designations',
        stateCitation: '314 CMR 21.00',
        details: 'The non-NSA areas are concentrated in a narrow mid-peninsula band. The vast majority of Falmouth\'s developed residential land — the entire south shore from Oyster Pond through Waquoit Bay, Falmouth Harbor, and the north shore harbors — is NSA-covered. Lots in the suggested I/A geoboundary area (shown in the WQMC January 2025 watershed presentation) are expected to remain on I/A rather than connect to sewer, meaning there is no sewer exception pathway for those lots under FHR 15.15.',
      },
      {
        id: 'FAL-T5-06',
        title: 'Mandatory Shared Systems (Denitrification Subdivisions)',
        status: 'exceeds_baseline',
        impact: 'high',
        localRule: 'Subdivisions subject to denitrification requirements must use shared systems meeting 12 mg/L total nitrogen limit. Individual on-site I/A systems prohibited in those subdivisions.',
        stateBaseline: 'Individual I/A systems permitted; no mandatory shared system requirement',
        gap: 'Individual nitrogen-reducing systems not allowed where shared system requirement applies',
        localRegulation: 'FHR 15.3(7)',
        stateCitation: '310 CMR 15.290-291',
        details: 'ADU additions in denitrification-required subdivisions cannot simply upgrade to an individual I/A system — they must tie into the subdivision\'s shared system. If shared system capacity is capped or if adding flow triggers shared system upgrades, ADU feasibility may be significantly constrained.',
      },
      {
        id: 'FAL-T5-07',
        title: 'Bedroom Definition',
        status: 'consistent',
        impact: 'neutral',
        localRule: 'DEP standard bedroom definition (DEQE correspondence 935-2160, October 22, 1985)',
        stateBaseline: 'Any space designed to furnish minimum isolation for sleeping, including den, study, sewing room, sleeping loft, enclosed porch',
        gap: 'None identified',
        localRegulation: 'FHR 15.5(3)(d)',
        stateCitation: '310 CMR 15.002',
        details: 'Falmouth adopts the standard DEP bedroom definition. Consistent with Title 5 and state practice.',
      },
      {
        id: 'FAL-T5-08',
        title: 'Bedroom Reallocation Policy',
        status: 'needs_review',
        impact: 'moderate',
        localRule: 'Not addressed in FHR regulations',
        stateBaseline: 'Not explicitly addressed statewide; emerging practice',
        gap: 'Unknown whether Falmouth BoH accepts bedroom reallocation to avoid triggering flow increase',
        localRegulation: 'No specific regulation identified',
        stateCitation: '310 CMR 15.002; 310 CMR 15.203',
        details: 'Bedroom reallocation has elevated significance in Falmouth because FHR 15.15 explicitly defines new construction to include flow increases. If reallocation avoids any increase in actual or design flow, the ADU addition may not qualify as new construction under FHR 15.15 — potentially avoiding the mandatory I/A requirement entirely. Given Cape Cod\'s nitrogen sensitivity context and the BoH\'s history of stringent regulation, informal practice here matters. Direct inquiry to the Falmouth Health Department is recommended.',
      },
      {
        id: 'FAL-T5-09',
        title: 'DEP Watershed Permit — Future Universal I/A Mandate',
        status: 'needs_review',
        impact: 'critical',
        localRule: 'DEP has designated 14 coastal ponds in Falmouth as NSAs. Falmouth has filed Notices of Intent for 4 watershed permits. If watershed permits are not obtained, all homes in affected watersheds must upgrade to BANRT (≤10 mg/L TN) by approximately 2030.',
        stateBaseline: 'No equivalent mandatory retrofit requirement',
        gap: 'Forward-looking universal I/A mandate covering most of developed Falmouth by ~2030',
        localRegulation: 'DEP Watershed Permits (314 CMR 21.00); FHR 15.15',
        stateCitation: '314 CMR 21.00',
        details: 'ADU additions that increase design flow in NSA watersheds already trigger mandatory I/A now under FHR 15.15. The watershed permit timeline means existing homes without ADUs face potential mandatory I/A retrofit by 2030. A homeowner adding an ADU today and installing I/A locks in a 15–20 year sewer deferral credit under FHR 15.15(4)(a) and avoids doing the upgrade twice. This reframes mandatory I/A from a pure cost to a partially strategic decision for properties in the suggested I/A geoboundary.',
        sourcingNote: 'Timeline based on WQMC Presentation, Falmouth\'s Watersheds, January 13, 2025. Exact dates subject to DEP permitting schedule.',
      },
    ],
    sources: [
      { label: 'Falmouth Health Regulations FHR-15.0', url: 'https://ecode360.com/FA1385' },
      { label: 'FHR 15.15 — I/A Systems for New Construction (Version 10.6, August 2025)', url: 'https://www.falmouthma.gov/DocumentCenter/View/FHR-15-15' },
      { label: 'WQMC Presentation — Falmouth\'s Watersheds and NSAs (January 13, 2025)', url: 'https://www.falmouthma.gov/DocumentCenter/View/WQMC-Watersheds' },
      { label: '310 CMR 15.211 — Minimum Setback Distances', url: 'https://www.law.cornell.edu/regulations/massachusetts/310-CMR-15-211' },
      { label: '314 CMR 21.00 — Watershed Permit Regulations', url: 'https://www.mass.gov/regulations/314-CMR-2100' },
    ],
  },
  {
    slug: 'nantucket',
    name: 'Nantucket',
    county: 'Nantucket County',
    regulatoryLayer: 'Nantucket Board of Health Local Regulations 64.00 and 50.00',
    stateBaseline: '310 CMR 15.000 (Title 5 of the State Environmental Code)',
    localAuthority: 'M.G.L. c. 111, § 31',
    lastReviewed: '2026-03-07',
    bottomLine: "Nantucket operates the most restrictive Board of Health septic regime of any Massachusetts town reviewed. A 300-foot setback from designated Nitrogen, Phosphorus, and Pathogen Sensitive Areas is the dominant constraint — given that NSA designations cover six of the island's nine named watersheds (all except the direct ocean-draining areas), this setback functionally limits where any septic construction can occur on the vast majority of Nantucket lots. Mandatory I/A technology with enhanced nutrient removal applies to all new construction and all system repairs/upgrades in sensitive areas, adding $15,000–$30,000+ in upfront cost plus annual service contracts recorded at the Registry of Deeds. The Nantucket bedroom definition is materially stricter than the DEP standard: open-plan areas exceeding 400 sq ft and 50% of a floor plate count as two bedrooms, and finished basements with a full bathroom count as one bedroom regardless of use. Separately, Regulation 50.00 creates a 'technical failure' standard based on separation distance alone — a system that is functioning normally but sits less than 6 ft above seasonal high water in an NSA is technically failed, forcing full system replacement rather than mere expansion when an ADU is added.",
    provisions: [
      {
        id: 'NAN-T5-01',
        title: 'Sensitive Area Setback',
        status: 'exceeds_baseline',
        impact: 'critical',
        localRule: '300 ft from any designated Nitrogen, Phosphorus, or Pathogen Sensitive Area. Separately, 300 ft from down-gradient surface water body for phosphorous loading — applies to repairs and upgrades, not just new construction.',
        stateBaseline: '50 ft from bordering vegetated wetland or surface water',
        gap: '6× the state minimum',
        localRegulation: 'Regulation 64.04(A); 64.04(C)(2)',
        stateCitation: '310 CMR 15.211',
        details: 'The 300 ft setback is the controlling constraint for nearly all Nantucket lots. Sensitive area designations cover the recharge areas draining to Nantucket Harbor, Sesachacha Pond, Madaket Harbor/Hither Creek, Hummock Pond, Long Pond, and Miacomet Pond — six of nine named watersheds. On many lots, compliant placement is geometrically impossible without a variance or pre-existing lot relief under Regulation 64.06. The phosphorous 300 ft requirement from down-gradient surface water bodies applies even to system repairs and upgrades.',
      },
      {
        id: 'NAN-T5-02',
        title: 'Groundwater Separation (Nitrogen Sensitive Areas)',
        status: 'exceeds_baseline',
        impact: 'high',
        localRule: '6 ft above maximum groundwater elevation in nitrogen sensitive areas. 5 ft in non-NSA areas and for I/A systems with enhanced nutrient removal in NSA areas.',
        stateBaseline: '4 ft in slow-perc soils; 5 ft in fast-perc soils (≤2 min/inch)',
        gap: '+1 to +2 ft depending on soil type and area designation',
        localRegulation: 'Regulation 64.03(A), (B), (C)',
        stateCitation: '310 CMR 15.212',
        details: 'The 6 ft requirement in NSAs is particularly binding given Nantucket\'s shallow water table in coastal zones. Critically, Regulation 50.00 defines "technical failure" as separation distance less than 6 ft from groundwater in documented NSA areas — regardless of whether the system is otherwise functioning. A system that passes a standard Title 5 inspection but sits 4–5 ft above seasonal high groundwater in an NSA is technically failed under Nantucket\'s definitions, forcing full system replacement rather than expansion when an ADU is added.',
      },
      {
        id: 'NAN-T5-03',
        title: 'Technical Failure Definition',
        status: 'exceeds_baseline',
        impact: 'high',
        localRule: 'A system is in technical failure if groundwater separation is less than 6 ft in documented NSA areas, or less than 5 ft outside NSA areas — regardless of whether the system is otherwise functioning operationally.',
        stateBaseline: 'System failure defined primarily by operational/hydraulic conditions — surface breakout, backup, cesspool status',
        gap: 'Separation distance deficiency alone constitutes failure in Nantucket, even for a normally functioning system',
        localRegulation: 'Regulation 50.00 — Definitions (Technical Failure)',
        stateCitation: '310 CMR 15.303',
        details: 'Many older Nantucket systems were built to the 4 ft Title 5 standard. An ADU addition on a lot with a 4–5 ft separation system in an NSA does not just need flow capacity — it needs a complete system replacement meeting the 6 ft standard. This is a hidden cost multiplier that will not appear in a standard Title 5 inspection report. Builders and lenders evaluating Nantucket ADU feasibility should request groundwater separation measurements from any existing Title 5 inspection, not just the pass/fail result.',
        sourcingNote: 'Technical failure definition confirmed in Regulation 50.00 (Local Regulation definitions, effective January 1, 2005, amended November 19, 2015).',
      },
      {
        id: 'NAN-T5-04',
        title: 'Mandatory I/A Technology (NSA New Construction and Repairs)',
        status: 'exceeds_baseline',
        impact: 'high',
        localRule: 'All new construction in NSA areas must use I/A technology with enhanced nitrogen/phosphorous removal (64.03(B)). All repairs and upgrades of failed systems must incorporate I/A technology with enhanced nutrient removal (64.03(D)). Service contract requirement recorded at Nantucket Registry of Deeds.',
        stateBaseline: 'I/A technology not required for most systems; standard gravity systems permitted',
        gap: 'Mandatory technology upgrade for all NSA new construction and all system repairs; significant cost differential',
        localRegulation: 'Regulation 64.03(B), (D)',
        stateCitation: '310 CMR 15.280-289',
        details: 'I/A systems typically cost $15,000–$30,000+ above a conventional system, plus annual inspection and service contracts. The service contract requirement is recorded at the Registry of Deeds, encumbering the property. For ADU additions that require system upgrade or expansion — which most will — this cost is unavoidable in sensitive areas. The annual O&M obligation persists for the life of the system.',
      },
      {
        id: 'NAN-T5-05',
        title: 'Bedroom Definition',
        status: 'exceeds_baseline',
        impact: 'high',
        localRule: 'A bedroom is any habitable space ≥70 sq ft, ≥7 ft ceiling, with electrical service, ventilation, and one window, separated by a full floor-to-ceiling wall. An undivided room area exceeding 50% of any single floor and exceeding 400 sq ft counts as two bedrooms for design flow. A finished basement containing at least one full bathroom counts as one bedroom.',
        stateBaseline: 'DEP 1985 definition (DEQE 935-2160) — spaces designed for minimum sleeping isolation',
        gap: 'Open-plan ADUs and finished basements may generate higher design flow than the DEP standard would produce',
        localRegulation: 'Regulation 50.00 — Definitions (Bedroom)',
        stateCitation: '310 CMR 15.002',
        details: 'A 900 sq ft ADU with an open-plan main floor exceeding 400 sq ft and more than half the floor plate could be treated as a 2-bedroom unit for flow purposes even if marketed as a studio. A finished basement with a bathroom is automatically one bedroom regardless of intended use. Engineers designing ADUs on Nantucket must account for these rules in flow calculations — the design flow consequences are significant on a 300 ft setback lot where system capacity is already constrained.',
      },
      {
        id: 'NAN-T5-06',
        title: 'H-20 Wheel Loading (Universal)',
        status: 'exceeds_baseline',
        impact: 'moderate',
        localRule: 'All systems must be installed to withstand H-20 wheel loading. Access and inspection covers minimum 18 inches diameter, medium or heavy duty cast iron.',
        stateBaseline: 'H-20 loading required only where vehicular loads apply (site-specific)',
        gap: 'Universal structural requirement adds engineering and material cost to all installations regardless of site',
        localRegulation: 'Regulation 64.04(E)(1); 64.05(B)',
        stateCitation: '310 CMR 15.000',
        details: 'H-20 loading (80,000 lb gross vehicle weight rating) is a traffic-load standard typically applied near roadways. Requiring it universally increases system construction cost on all Nantucket ADU-related system expansions.',
      },
      {
        id: 'NAN-T5-07',
        title: 'Pre-Existing Lot Relief',
        status: 'consistent',
        impact: 'moderate',
        localRule: 'Lots recorded before August 31, 1990 may seek relief from 300 ft and 6 ft standards under Regulation 64.06, requiring maximum feasible compliance — system positioned as close to compliant as lot geometry allows.',
        stateBaseline: 'Variance pathway available under Title 5',
        gap: 'Structurally similar to Title 5 variance; maximum feasible compliance standard requires comprehensive siting analysis',
        localRegulation: 'Regulation 64.06',
        stateCitation: '310 CMR 15.410-15.413',
        details: 'Pre-1990 lots have an administrative pathway, but must demonstrate the system is positioned as close to the 300 ft/6 ft targets as lot geometry allows. For pre-1990 ADU projects, all feasible alternatives must be documented before the Board will grant relief.',
      },
      {
        id: 'NAN-T5-08',
        title: 'Bedroom Reallocation Policy',
        status: 'needs_review',
        impact: 'moderate',
        localRule: 'Not addressed in Local Regulation 64.00 or 50.00',
        stateBaseline: 'Not explicitly addressed statewide; emerging practice',
        gap: 'Unknown; practical significance may be lower than on the mainland given NSA-triggered I/A requirements apply independent of flow calculation in many cases',
        localRegulation: 'No specific regulation identified',
        stateCitation: '310 CMR 15.002; 310 CMR 15.203',
        details: 'Bedroom reallocation may be less impactful on Nantucket than elsewhere because I/A technology and 300 ft setback requirements can apply independent of flow calculation. However, if reallocation keeps total flow below the 330 gpd combined-well trigger (Regulation 64.04(B)(2)), it avoids the 25% TN reduction requirement for lots with private wells. Direct inquiry to the Nantucket Board of Health is recommended.',
      },
    ],
    sources: [
      { label: 'Nantucket Board of Health Local Regulation 64.00 — On Site Sewage Disposal Systems', url: 'https://www.nantucket-ma.gov/DocumentCenter/View/Regulation-64' },
      { label: 'Nantucket Board of Health Local Regulation 50.00 — Definitions', url: 'https://www.nantucket-ma.gov/DocumentCenter/View/Regulation-50' },
      { label: 'Nantucket Watershed Map (KMZ)', url: 'https://www.nantucket-ma.gov/GIS' },
      { label: '310 CMR 15.211 — Minimum Setback Distances', url: 'https://www.law.cornell.edu/regulations/massachusetts/310-CMR-15-211' },
      { label: '310 CMR 15.212 — Depth to Groundwater', url: 'https://www.law.cornell.edu/regulations/massachusetts/310-CMR-15-212' },
    ],
  },
  {
    slug: 'plymouth',
    name: 'Plymouth',
    county: 'Plymouth County',
    regulatoryLayer: 'Plymouth Board of Health Supplements to Title 5 (created April 13, 2011; amended October 24, 2023)',
    stateBaseline: '310 CMR 15.000 (Title 5 of the State Environmental Code)',
    localAuthority: 'M.G.L. c. 111, § 31',
    lastReviewed: '2026-03-07',
    bottomLine: "Plymouth's Title 5 supplement is among the least restrictive reviewed. Section 5 of the supplement explicitly states that Plymouth follows strict Title 5 code on new construction setback distances — no local modifications. There are no nitrogen sensitive area designations, no enhanced wetland setbacks, and no mandatory I/A technology requirements. The primary septic friction for ADU projects is upstream of design: cesspools constitute automatic failure upon any building permit application, and structures served by systems designed between 1962 and 1978 require a full Title 5 inspection — with documented reserve area — before the Health Department will sign off on a building permit for additions. An ADU addition on a pre-1978 property with an undocumented system creates a mandatory inspection and potential remediation requirement before construction can proceed. Plymouth is one of the more feasible septic environments in southeastern Massachusetts for ADU construction.",
    provisions: [
      {
        id: 'PLY-T5-01',
        title: 'New Construction Setback Distances',
        status: 'consistent',
        impact: 'neutral',
        localRule: 'Plymouth explicitly follows strict Title 5 code on new construction setback distances. No local modifications.',
        stateBaseline: '50 ft wetland/surface water; 100 ft private well; 25 ft irrigation well; 10 ft property line; 20 ft foundation',
        gap: 'None',
        localRegulation: 'Regulation 2, Section 5 (revised January 26, 2011)',
        stateCitation: '310 CMR 15.211',
        details: 'Plymouth previously had local setback modifications and revised them in January 2011 to remove them. The explicit "we follow strict Title 5" language is significant — it is a deliberate policy choice to not exceed the baseline. For ADU new construction, the statewide Title 5 setback distances apply without enhancement.',
      },
      {
        id: 'PLY-T5-02',
        title: 'Cesspool Automatic Failure',
        status: 'exceeds_baseline',
        impact: 'critical',
        localRule: 'Cesspools and cesspits constitute automatic failure when found at time of inspection, when making major or minor additions requiring a building permit, or at time of property sale or title transfer.',
        stateBaseline: 'Cesspools are nonconforming systems but not automatically failed under all circumstances',
        gap: 'Any building permit for additions forces cesspool disclosure and failure determination — broader trigger than Title 5',
        localRegulation: 'Regulation 2, Sections 3.1 and 3.2',
        stateCitation: '310 CMR 15.303',
        details: 'Plymouth has a significant stock of older housing, particularly in lakefront and rural areas, that may still have cesspools. An ADU addition on a property with a cesspool does not just trigger a flow calculation — it triggers mandatory system replacement before the building permit can proceed. For lenders, this is a material underwriting risk on pre-1978 Plymouth properties with no documented septic upgrade history.',
      },
      {
        id: 'PLY-T5-03',
        title: 'Pre-1978 System Inspection Requirement',
        status: 'exceeds_baseline',
        impact: 'moderate',
        localRule: 'An approved Title V inspection report is required before the Health Department will sign off on a building permit for major or minor additions to structures served by systems designed between 1962 and 1978. Inspection must document location of all components including reserve area.',
        stateBaseline: 'No universal pre-permit inspection requirement for additions to existing structures',
        gap: 'Mandatory inspection step and reserve area documentation required for a substantial portion of Plymouth\'s housing stock',
        localRegulation: 'Regulation 2, Section 3.1',
        stateCitation: '310 CMR 15.300-304',
        details: 'Systems designed 1962–1978 cover a wide swath of Plymouth\'s suburban and lakefront development. ADU additions on these properties require a full Title 5 inspection as a prerequisite — not just a design review. If the inspection reveals failure or cesspool conditions, the system must be remediated before the ADU permit can advance. This is a sequencing constraint affecting project timelines and financing.',
      },
      {
        id: 'PLY-T5-04',
        title: 'Major Addition Definition',
        status: 'needs_review',
        impact: 'moderate',
        localRule: 'A Major Addition is any addition ≥70 sq ft in floor space with ≥7 ft floor-to-ceiling height. Exceptions include areas that do not increase daily flow: sheds, pools, porches, room expansions, remodeling without room configuration changes.',
        stateBaseline: 'Flow increase triggers system evaluation under Title 5; no specific sq ft threshold',
        gap: 'Local clarification of what constitutes a flow-triggering addition; 70 sq ft / 7 ft ceiling threshold is explicit',
        localRegulation: 'Regulation 1 — Definitions (Major Addition)',
        stateCitation: '310 CMR 15.203',
        details: 'An ADU of any meaningful size constitutes a Major Addition under this definition. This triggers the cesspool inspection requirement and the pre-1978 system inspection requirement. The exception language for areas that do not increase daily flow is relevant to the bedroom reallocation question — if reallocation is accepted and no net flow increase occurs, the ADU addition may qualify for the exception.',
      },
      {
        id: 'PLY-T5-05',
        title: 'I/A System Reporting Requirement',
        status: 'exceeds_baseline',
        impact: 'neutral',
        localRule: 'Effective January 1, 2024: all I/A systems and pressure distribution systems must report operation, maintenance, and monitoring results to Barnstable County Department of Health and Environment within 30 days of each maintenance event.',
        stateBaseline: 'Reporting requirements variable; not universally mandated to county at this frequency',
        gap: 'Additional administrative compliance obligation for any ADU project installing I/A or pressure distribution',
        localRegulation: 'Regulation 2, Section 8 (amended October 24, 2023)',
        stateCitation: '310 CMR 15.000',
        details: 'Low operational impact — this is a reporting obligation, not a design constraint. Notable that Plymouth (Plymouth County) directs reporting to Barnstable County DHCE. This may reflect a legacy of Cape Cod regional coordination or a specific interagency agreement. Worth confirming with Plymouth Health Department.',
      },
      {
        id: 'PLY-T5-06',
        title: 'Bedroom Reallocation Policy',
        status: 'needs_review',
        impact: 'moderate',
        localRule: 'Not addressed in the supplement',
        stateBaseline: 'Not explicitly addressed statewide; emerging practice',
        gap: 'Unknown; Plymouth\'s permissive posture on setbacks suggests potential receptiveness, but no documented policy exists',
        localRegulation: 'No specific regulation identified',
        stateCitation: '310 CMR 15.002; 310 CMR 15.203',
        details: 'Given Plymouth has no NSA designations and explicitly follows Title 5 baseline setbacks, bedroom reallocation has higher practical value here than in Falmouth or Nantucket — it could keep an ADU addition below the flow increase threshold entirely, potentially avoiding the pre-1978 inspection trigger and cesspool disclosure requirements under the Major Addition definition. Direct inquiry to Plymouth Health Department is recommended.',
      },
    ],
    sources: [
      { label: 'Plymouth Board of Health Supplements to Title 5 (April 13, 2011; amended October 24, 2023)', url: 'https://plymouth-ma.gov/DocumentCenter/View/1898/Title-5-Supplement---4-13-2011-PDF' },
      { label: '310 CMR 15.211 — Minimum Setback Distances', url: 'https://www.law.cornell.edu/regulations/massachusetts/310-CMR-15-211' },
      { label: '310 CMR 15.303 — Conditions Constituting Failure', url: 'https://www.law.cornell.edu/regulations/massachusetts/310-CMR-15-303' },
    ],
  },
  {
    slug: 'upton',
    name: 'Upton',
    county: 'Worcester County',
    regulatoryLayer: 'Town of Upton Board of Health Regulations Chapter 340 Article I — Title 5 Supplement',
    stateBaseline: '310 CMR 15.000 (Title 5 of the State Environmental Code)',
    localAuthority: 'M.G.L. c. 111, § 31',
    lastReviewed: '2026-03-07',
    bottomLine: "Upton's Title 5 supplement imposes two constraints that directly affect ADU septic feasibility: a doubled wetland setback (100 ft vs. Title 5's 50 ft) and a prohibition on new system construction in soils with percolation rates slower than 30 minutes per inch — half the 60 min/inch threshold Title 5 permits. The wetland setback applies to all septic systems, not just new construction, and references wetlands as classified by the Upton Conservation Commission, which may be broader than the Title 5 BVW definition. The percolation restriction means usable site area on a lot is limited to whatever can achieve ≤30 min/inch perc — on lots with variable glacial till soils, that may be a small fraction of the available area. Upton's bedroom definition also introduces an open-plan exclusion rule: a room is only excluded from bedroom count if it has a minimum 6-foot opening into an adjacent room other than a bathroom. Unlike Falmouth and Nantucket, Upton has no nitrogen sensitive area designations and no I/A technology requirements.",
    provisions: [
      {
        id: 'UPT-T5-01',
        title: 'Wetland Setback',
        status: 'exceeds_baseline',
        impact: 'critical',
        localRule: '100 ft from wetlands as classified by the Upton Conservation Commission',
        stateBaseline: '50 ft from bordering vegetated wetland or surface water',
        gap: '2× the state minimum (+50 ft)',
        localRegulation: '§340-3(A)',
        stateCitation: '310 CMR 15.211',
        details: 'The 100 ft rule applies to all septic systems — not just new construction — meaning ADU additions that require system expansion face the full requirement. Critically, the wetland delineation authority is the Upton Conservation Commission, not just the Title 5 definition of bordering vegetated wetland. Conservation Commission jurisdictional wetlands may be broader than the Title 5 BVW definition, potentially expanding the effective setback zone beyond what a standard Title 5 site assessment would show. Any ADU project near a wetland edge should obtain Conservation Commission delineation confirmation before committing to a design.',
      },
      {
        id: 'UPT-T5-02',
        title: 'Percolation Rate Restriction (New Construction)',
        status: 'exceeds_baseline',
        impact: 'high',
        localRule: 'New septic systems shall not be sited in areas with percolation rates slower than 30 min/inch. Soils between 30–60 min/inch may only be used for repair/upgrade of existing systems where no other suitable area exists, with Board of Health approval.',
        stateBaseline: 'Soils up to 60 min/inch acceptable for new construction',
        gap: 'New construction restricted to soils achieving ≤30 min/inch; Title 5 allows up to 60 min/inch',
        localRegulation: '§340-1(D)',
        stateCitation: '310 CMR 15.243',
        details: 'This cuts available site area on lots with slower-draining soils in half relative to Title 5. On a lot where the only feasible leaching location has 35–55 min/inch perc rates, an ADU addition cannot install a new system there — it is restricted to repair/upgrade of the existing system with Board approval. Upton\'s glacial till soils mean this is a real site-level constraint, not a theoretical one. For ADU projects requiring a new or expanded leaching facility, usable area is whatever can achieve ≤30 min/inch perc.',
      },
      {
        id: 'UPT-T5-03',
        title: 'Bedroom Definition — Open Plan Rule',
        status: 'exceeds_baseline',
        impact: 'moderate',
        localRule: 'For new construction or remodeling, a room is only excluded from bedroom count if it has a minimum 6-foot opening into another room (other than a bathroom). Dining room is explicitly listed as a potential bedroom. Pre-1978 dwellings assessed case-by-case.',
        stateBaseline: 'DEP 1985 definition (DEQE 935-2160) — spaces designed for minimum sleeping isolation; no explicit open-plan exclusion rule',
        gap: 'Open-plan ADU designs must provide 6-ft openings to exclude flex rooms from bedroom count; dining rooms may be counted as bedrooms',
        localRegulation: '§340-2(A)',
        stateCitation: '310 CMR 15.002',
        details: 'An ADU with a partially open den or flex room does not escape bedroom classification unless the opening to an adjacent space is at least 6 feet wide. Notably, Upton\'s definition includes dining room as a potential bedroom — the DEP standard does not. An ADU with a separate dining room and no 6-foot opening to an adjacent room could be counted as an additional bedroom for design flow purposes. Engineers and architects designing ADUs in Upton should plan floor layouts accounting for this rule.',
      },
      {
        id: 'UPT-T5-04',
        title: 'Testing Season Restriction',
        status: 'exceeds_baseline',
        impact: 'moderate',
        localRule: 'Deep hole and percolation testing for new homes is only permitted September 1 through May 31. Testing season closes June, July, and August.',
        stateBaseline: 'No testing season restriction',
        gap: '3-month testing blackout for new construction site assessment',
        localRegulation: '§340-1(A)',
        stateCitation: '310 CMR 15.000',
        details: 'ADU projects requiring new soil testing cannot get tests done in summer. For a project starting site assessment in June, the earliest testing date is September 1 — a potential 1–3 month delay depending on scheduling. This matters most for projects on lots where soil suitability has not been previously documented. Projects expanding an existing system with documented soil data may proceed without new testing.',
      },
      {
        id: 'UPT-T5-05',
        title: 'Inspector / Installer Conflict of Interest',
        status: 'consistent',
        impact: 'neutral',
        localRule: 'Any repairs to a system compelled by a failed Title 5 inspection must be completed by a licensed installer who had no participation in the Title 5 inspection for the property.',
        stateBaseline: 'No equivalent requirement',
        gap: 'Consumer protection provision; not a septic design constraint',
        localRegulation: '§340-6',
        stateCitation: '310 CMR 15.000',
        details: 'Builders who use a single firm for both inspection and installation will need separate parties for each function when a failed inspection reveals an upgrade is needed before an ADU building permit can proceed.',
      },
      {
        id: 'UPT-T5-06',
        title: 'Bedroom Reallocation Policy',
        status: 'needs_review',
        impact: 'moderate',
        localRule: 'Not addressed in the supplement',
        stateBaseline: 'Not explicitly addressed statewide; emerging practice',
        gap: 'Unknown; given Upton\'s strict bedroom definition (6-ft opening rule, dining room inclusion), reallocation has higher value as a mitigation strategy',
        localRegulation: 'No specific regulation identified',
        stateCitation: '310 CMR 15.002; 310 CMR 15.203',
        details: 'Upton\'s bedroom definition makes it easier to accidentally add bedrooms through ADU design — the 6-ft opening rule and dining room inclusion mean open-plan ADUs require careful floor plan review. Bedroom reallocation as a mitigation strategy has correspondingly higher value. The pre-1978 case-by-case bedroom assessment provision suggests the Upton BoH exercises discretion on bedroom counting, which may extend to reallocation. Direct inquiry to the Upton Board of Health is recommended.',
      },
    ],
    sources: [
      { label: 'Town of Upton Board of Health Regulations — Chapter 340 Article I, Title 5 Supplement', url: 'https://ecode360.com/UP3528' },
      { label: '310 CMR 15.211 — Minimum Setback Distances', url: 'https://www.law.cornell.edu/regulations/massachusetts/310-CMR-15-211' },
      { label: '310 CMR 15.243 — Percolation Standards', url: 'https://www.law.cornell.edu/regulations/massachusetts/310-CMR-15-243' },
    ],
  },
  {
    slug: 'east-bridgewater',
    name: 'East Bridgewater',
    county: 'Plymouth County',
    regulatoryLayer: 'East Bridgewater Board of Health Groundwater Protection Regulations (adopted July 17, 2007)',
    stateBaseline: '310 CMR 15.000 (Title 5 of the State Environmental Code)',
    localAuthority: 'M.G.L. c. 111, §§ 31 and 122',
    lastReviewed: '2026-03-07',
    bottomLine: "East Bridgewater has not adopted a Title 5 supplement. Septic system design for ADU projects follows the state baseline under 310 CMR 15.000 without local modification — no enhanced setbacks, no nitrogen sensitive area designations, no mandatory I/A technology, no local bedroom definition changes. The only local Board of Health overlay is a Zone II aquifer protection regulation (adopted 2007) that restricts hazardous land uses and impervious cover within aquifer recharge areas. The impervious cover limit (15% of lot area or 2,500 sq ft, whichever is greater) is the only provision with direct ADU implications — lots where the existing structure plus ADU footprint plus driveway would push impervious coverage over the threshold require a stormwater recharge system as a condition of BoH approval. East Bridgewater is among the least constrained towns in southeastern Massachusetts for ADU septic compliance.",
    provisions: [
      {
        id: 'EB-T5-01',
        title: 'Title 5 Setback Distances',
        status: 'consistent',
        impact: 'neutral',
        localRule: 'No Title 5 supplement adopted. State baseline applies without modification.',
        stateBaseline: '50 ft wetland/surface water; 100 ft private well; 25 ft irrigation well; 10 ft property line; 20 ft foundation',
        gap: 'None',
        localRegulation: 'No local supplement',
        stateCitation: '310 CMR 15.211',
        details: 'East Bridgewater is one of few towns in southeastern Massachusetts with no local Title 5 modifications. ADU new construction follows state baseline setbacks in full.',
      },
      {
        id: 'EB-T5-02',
        title: 'Impervious Cover Limit (Zone II)',
        status: 'exceeds_baseline',
        impact: 'moderate',
        localRule: 'Land uses resulting in impervious cover exceeding 15% of lot area or 2,500 sq ft (whichever is greater) are prohibited in Zone II unless a stormwater recharge system is provided that does not degrade groundwater quality.',
        stateBaseline: 'No impervious cover limit under Title 5',
        gap: 'Site planning constraint for Zone II lots where ADU addition pushes total impervious coverage over threshold',
        localRegulation: 'Groundwater Protection Regulations — Prohibitions (Section 7)',
        stateCitation: '310 CMR 22.00 (Zone II definition)',
        details: 'On smaller lots, 2,500 sq ft is the floor trigger — but 15% kicks in on lots above roughly 16,700 sq ft (approximately 0.4 acres), which covers a large portion of residential lots. The cumulative footprint of existing structure, driveway, proposed ADU, and any accessory structures must be evaluated against this threshold. Where it is exceeded, a stormwater recharge system is required as a BoH approval condition.',
      },
      {
        id: 'EB-T5-03',
        title: 'Soil Removal Restriction Near Groundwater (Zone II)',
        status: 'exceeds_baseline',
        impact: 'moderate',
        localRule: 'Removal of soil, loam, sand, gravel, or mineral substances within 4 feet of the historical high groundwater table elevation is prohibited in Zone II. Exceptions: materials removed and re-deposited within 45 days to achieve final grade >4 ft above historical high water; excavations for building foundations or utility installation.',
        stateBaseline: 'No equivalent restriction under Title 5',
        gap: 'Septic system excavation in shallow groundwater areas within Zone II may require confirmation that work falls within the foundation/utility exception',
        localRegulation: 'Groundwater Protection Regulations — Prohibitions (Section 6)',
        stateCitation: '310 CMR 22.00',
        details: 'For ADU projects requiring new leaching field excavation in Zone II areas with shallow groundwater, this provision adds a compliance question. Leaching field installation would likely qualify under the foundation/utility exception but should be confirmed with the East Bridgewater Board of Health prior to permitting.',
      },
      {
        id: 'EB-T5-04',
        title: 'Bedroom Reallocation Policy',
        status: 'needs_review',
        impact: 'moderate',
        localRule: 'Not addressed; no Title 5 supplement adopted',
        stateBaseline: 'Not explicitly addressed statewide; emerging practice',
        gap: 'Unknown; absence of local supplement suggests BoH follows state practice',
        localRegulation: 'No specific regulation identified',
        stateCitation: '310 CMR 15.002; 310 CMR 15.203',
        details: 'Given East Bridgewater has no local Title 5 modifications, the bedroom reallocation question defaults to state-level practice and the BoH\'s informal position. The absence of restrictive local rules suggests this is one of the more receptive environments for bedroom reallocation as an ADU feasibility pathway.',
      },
    ],
    sources: [
      { label: 'East Bridgewater Board of Health — Groundwater Protection Regulations (July 17, 2007)', url: 'https://www.eastbridgewaterma.gov/1985/Groundwater-Protection-Regulations' },
      { label: '310 CMR 15.211 — Minimum Setback Distances', url: 'https://www.law.cornell.edu/regulations/massachusetts/310-CMR-15-211' },
      { label: '310 CMR 22.00 — Zone II Definition', url: 'https://www.mass.gov/regulations/310-CMR-2200' },
    ],
  },
  {
    slug: 'weston',
    name: 'Weston',
    county: 'Middlesex County',
    regulatoryLayer: 'Chapter VI — Sewage Disposal Systems (approved December 5, 2001; Section 1.8a amended September 18, 2002)',
    stateBaseline: '310 CMR 15.000 (Title 5 of the State Environmental Code)',
    localAuthority: 'M.G.L. c. 111, § 31',
    lastReviewed: '2026-03-08',
    bottomLine: "Weston's Chapter VI sewage disposal regulations are explicitly described as 'a more environmentally restrictive code than required by Title V.' Much of Weston lies within the City of Cambridge watershed, driving enhanced wetland protection. The regulations double the Title 5 wetland setback to 100 feet, require all residential leaching areas to be sized at 150% of Title 5 minimums (to accommodate potential garbage grinder use), impose a 20-foot foundation setback from leaching facilities (vs. Title 5's 10 feet), and ban all septic system construction from December 1 through the end of February. In high groundwater areas where the water table is less than 2 feet below the surface, wastewater loading is capped at 660 gallons per day per acre. Septic additives — enzymes, degreasers, acids — are prohibited without specific written Board of Health authorization. These provisions layer onto standard Title 5 requirements to create a materially more constrained environment for ADU septic design on lots near wetlands or in high groundwater zones.",
    provisions: [
      {
        id: 'WES-T5-01',
        title: 'Wetland Setback',
        status: 'exceeds_baseline',
        impact: 'critical',
        localRule: '100 ft from wetlands (as defined in M.G.L. Chapter 131, Section 40)',
        stateBaseline: '50 ft from bordering vegetated wetlands',
        gap: '2× the state minimum (+50 ft)',
        localRegulation: 'Section 2.5',
        stateCitation: '310 CMR 15.211',
        details: "Weston's 100-foot wetland setback reflects the town's position within the Cambridge watershed. The regulation references the Wetlands Protection Act definition (M.G.L. c. 131, § 40), which may be broader than the Title 5 BVW definition. On lots near wetland edges, this doubles the exclusion zone for leaching facility placement relative to the state baseline.",
      },
      {
        id: 'WES-T5-02',
        title: 'Leaching Area Increase',
        status: 'exceeds_baseline',
        impact: 'high',
        localRule: '150% of Title 5 leaching area requirements for all residential systems',
        stateBaseline: '100% of calculated leaching area per 310 CMR 15.242',
        gap: '+50% above state minimum',
        localRegulation: 'Section 2.4',
        stateCitation: '310 CMR 15.242',
        details: "All residential sewage disposal systems must be designed for a 150% increase over Title 5 requirements. The stated rationale is to prolong system life in the event a garbage grinder is installed. This effectively increases the minimum footprint of any leaching facility by 50%, reducing the buildable area available on constrained lots regardless of whether a garbage grinder is actually present.",
      },
      {
        id: 'WES-T5-03',
        title: 'Foundation Setback',
        status: 'exceeds_baseline',
        impact: 'moderate',
        localRule: '20 ft from foundation wall or footing to leaching facility; 10 ft from septic tank',
        stateBaseline: '10 ft from building foundation to soil absorption system',
        gap: '+10 ft above state minimum for leaching facility',
        localRegulation: 'Section 2.5',
        stateCitation: '310 CMR 15.211',
        details: "The doubled foundation setback for leaching facilities reduces the usable area between an existing structure and a proposed leaching field. On lots where the ADU is sited near the primary leaching area, this 20-foot buffer may force system redesign or alternative placement.",
      },
      {
        id: 'WES-T5-04',
        title: 'Winter Construction Ban',
        status: 'exceeds_baseline',
        impact: 'moderate',
        localRule: 'No septic system construction December 1 through end of February. Board may allow exceptions for occupied residences posing a health or safety hazard.',
        stateBaseline: 'No seasonal construction restriction under Title 5',
        gap: '3-month construction blackout',
        localRegulation: 'Section 1.3',
        stateCitation: '310 CMR 15.000',
        details: "ADU projects requiring new septic construction or system expansion cannot proceed with site work during the winter months. The exception is limited to occupied residences posing a health or safety hazard — new ADU construction would not qualify. Projects permitted in the fall face a hard deadline or a 3-month delay.",
      },
      {
        id: 'WES-T5-05',
        title: 'Septic Additives Prohibited',
        status: 'exceeds_baseline',
        impact: 'moderate',
        localRule: 'Enzymes, degreasers, acids, or other additives prohibited in any septic system without specific written Board of Health authorization',
        stateBaseline: 'No blanket prohibition on septic additives under Title 5',
        gap: 'Complete prohibition without prior BOH written approval',
        localRegulation: 'Section 5.4',
        stateCitation: '310 CMR 15.000',
        details: "This is an operational constraint rather than a design constraint. Homeowners with ADU septic systems cannot use commercially available septic treatments without Board of Health written authorization. The provision reflects Weston's conservative approach to system maintenance and long-term soil absorption capacity.",
      },
      {
        id: 'WES-T5-06',
        title: 'High Groundwater Loading Limit',
        status: 'exceeds_baseline',
        impact: 'high',
        localRule: 'Maximum 660 gpd/acre where groundwater is less than 2 ft below natural ground surface',
        stateBaseline: 'No equivalent area-wide loading limit under Title 5 at this groundwater depth',
        gap: 'Site-density cap in shallow groundwater zones',
        localRegulation: 'Section 2.12',
        stateCitation: '310 CMR 15.000',
        details: "In areas with high groundwater (less than 2 feet below natural grade), the 660 gpd/acre loading limit constrains total wastewater output per acre. A typical 3-bedroom home generates 330 gpd; adding a 1-bedroom ADU at 110 gpd brings the total to 440 gpd. On lots under approximately 0.67 acres in high groundwater zones, the combined flow may approach or exceed the loading limit, potentially blocking ADU construction without lot-specific analysis.",
      },
      {
        id: 'WES-T5-07',
        title: 'Bedroom Reallocation Policy',
        status: 'needs_review',
        impact: 'critical',
        localRule: "Not addressed in Chapter VI. Weston's regulations require permits for building additions and evaluation of existing system adequacy (Section 1.2), but do not specifically address bedroom reallocation between a principal dwelling and an ADU.",
        stateBaseline: "Title 5 (310 CMR 15.000) calculates septic capacity based on total bedroom count on a lot. No state-level provision specifically addresses bedroom reallocation between a principal dwelling and an ADU.",
        gap: 'No explicit local policy — standard practice emerging statewide but not codified in Weston',
        localRegulation: 'No specific regulation identified',
        stateCitation: '310 CMR 15.002 (bedroom definition), 310 CMR 15.203 (design flow)',
        details: "Bedroom reallocation — reducing the main house bedroom count and allocating that capacity to the ADU — is emerging as the primary feasibility pathway for ADU construction on septic-constrained lots across Massachusetts. Given Weston's 150% leaching area requirement (WES-T5-02) and 100-foot wetland setback (WES-T5-01), many lots cannot support a new or expanded system. Reallocation that avoids a net flow increase could be the only viable pathway. Section 1.2 requires BOH approval of the existing system for building additions — whether reallocation is treated as a flow-neutral modification or triggers a full system review is unresolved. Direct inquiry to the Weston Board of Health is recommended.",
        sourcingNote: "This provision is based on cross-town pattern analysis and builder interviews, not Weston-specific BOH documentation. Verification with Weston's BOH is recommended before relying on this pathway.",
      },
    ],
    sources: [
      { label: 'Weston Board of Health — Chapter VI, Sewage Disposal Systems', url: 'https://www.westonma.gov/216/Board-of-Health-Regulations-PDF' },
      { label: 'Weston Board of Health — Septic System Repair/Construction Requirements', url: 'https://www.westonma.gov/DocumentCenter/View/96/Requirements-for-Septic-System-Repair-Construction-or-Maintenance-PDF' },
      { label: 'Weston Board of Health — Home Page', url: 'https://www.westonma.gov/400/Board-of-Health' },
      { label: '310 CMR 15.211 — Minimum Setback Distances', url: 'https://www.law.cornell.edu/regulations/massachusetts/310-CMR-15-211' },
    ],
  },
  {
    slug: 'sudbury',
    name: 'Sudbury',
    county: 'Middlesex County',
    regulatoryLayer: 'Rules & Regulations Governing the Subsurface Disposal of Sewage (adopted February 15, 1984; amended through March 26, 1998)',
    stateBaseline: '310 CMR 15.000 (Title 5 of the State Environmental Code)',
    localAuthority: 'M.G.L. c. 111, § 31',
    lastReviewed: '2026-03-08',
    bottomLine: "Sudbury's septic regulations impose several constraints that exceed Title 5 baselines. In Zone II aquifer protection areas, groundwater separation increases to 6 feet — above the 5-foot/4-foot Title 5 standard. Leaching beds are prohibited entirely; only trenches and pit/galleries are permitted. Sewage pumps of any type are prohibited from residential systems unless a variance is granted by the Board of Health, and the Board's variance standard is strict — neither financial hardship nor past practices are considered adequate reasons. Sudbury's separate irrigation well regulations require a 100-foot setback from septic systems and a 100-foot setback from wetlands, far exceeding the Title 5 baseline of 25 feet from irrigation wells. When construction in fill is required, both the primary area and the expansion area must be prepared. These layered restrictions narrow the design options available for ADU septic systems, particularly on lots in Zone II areas or near wetlands.",
    provisions: [
      {
        id: 'SUD-T5-01',
        title: 'Groundwater Separation in Zone II',
        status: 'exceeds_baseline',
        impact: 'high',
        localRule: '6 ft from bottom of leaching facility to high groundwater in Zone II aquifer protection areas',
        stateBaseline: '5 ft above high groundwater in fast-perc soils (≤2 min/inch); 4 ft in slower soils',
        gap: '+1 to +2 ft above state minimum depending on soil type',
        localRegulation: 'Section VIII',
        stateCitation: '310 CMR 15.212(1)(b)',
        details: "The 6-foot groundwater separation requirement in Zone II areas adds vertical clearance above Title 5 minimums. On lots with shallow groundwater in aquifer recharge zones, this can push the system elevation higher, requiring more fill construction and increasing both cost and visual impact. Section IX separately addresses subsurface drains to lower groundwater — but the drain must be installed and proven functional before the BOH will issue a permit.",
      },
      {
        id: 'SUD-T5-02',
        title: 'Leaching Beds Prohibited',
        status: 'exceeds_baseline',
        impact: 'high',
        localRule: 'Leaching beds not permitted. Only trenches and pit/galleries allowed. Leaching area calculated on sidewall area only.',
        stateBaseline: 'Leaching beds permitted as a soil absorption system option under 310 CMR 15.242',
        gap: 'Eliminates one of three standard SAS configurations',
        localRegulation: 'Section III',
        stateCitation: '310 CMR 15.242',
        details: "Leaching beds — a single large excavation rather than separate trenches — are a common space-saving design option under Title 5. Sudbury's prohibition forces the use of trenches or galleries, which typically require a larger total footprint due to separation distances between trenches. For ADU projects on constrained lots, this eliminates a design option that might otherwise fit within the available area.",
      },
      {
        id: 'SUD-T5-03',
        title: 'Sewage Pumps Prohibited',
        status: 'exceeds_baseline',
        impact: 'high',
        localRule: 'Sewage pumps of any type prohibited from residential systems unless variance granted by Board of Health',
        stateBaseline: 'Pumped systems permitted; pressure distribution systems addressed in 310 CMR 15.254',
        gap: 'Pump systems require variance; BOH variance standard excludes financial hardship as grounds',
        localRegulation: 'Section VI',
        stateCitation: '310 CMR 15.254',
        details: "Sewage pumps enable system placement at elevations and distances that gravity systems cannot reach — a critical flexibility for ADU projects where the leaching field must be located far from or uphill from the dwelling. Sudbury's blanket prohibition means pump-dependent designs require a variance. The Board's variance policy (Section XVI) explicitly states that neither financial hardship nor past practices are adequate reasons for granting variances — the standard is limited to public health considerations.",
      },
      {
        id: 'SUD-T5-04',
        title: 'Irrigation Well Setback from Septic',
        status: 'exceeds_baseline',
        impact: 'critical',
        localRule: '100 ft from irrigation well to sewage disposal system',
        stateBaseline: '25 ft from irrigation well to soil absorption system',
        gap: '4× the state minimum (+75 ft)',
        localRegulation: 'In-Ground Irrigation Systems Regulations (Article XXVII, revised 4/4/06)',
        stateCitation: '310 CMR 15.211',
        details: "Sudbury's irrigation well setback of 100 feet from septic systems is four times the Title 5 baseline. On lots with existing irrigation wells, this creates a 100-foot exclusion radius around the well for any septic system placement. Combined with the 100-foot wetland setback for irrigation wells, properties with both irrigation wells and wetland frontage face significantly constrained siting options for ADU-related septic expansion.",
      },
      {
        id: 'SUD-T5-05',
        title: 'Irrigation Well Setback from Wetlands',
        status: 'exceeds_baseline',
        impact: 'high',
        localRule: '100 ft from irrigation well to wetland or vernal pool',
        stateBaseline: '50 ft from bordering vegetated wetland for septic components',
        gap: '2× the state wetland setback (+50 ft) applied to irrigation wells',
        localRegulation: 'In-Ground Irrigation Systems Regulations (Article XXVII)',
        stateCitation: '310 CMR 15.211',
        details: "Irrigation wells must be sited at least 100 feet from any wetland or vernal pool. While this is a well-siting restriction rather than a septic system restriction, it interacts with septic layout because the irrigation well's 100-foot septic setback (SUD-T5-04) constrains where septic components can be placed relative to the well. On lots with wetlands, the combined effect narrows both well and septic siting options.",
      },
      {
        id: 'SUD-T5-06',
        title: 'Fill Construction Requirements',
        status: 'exceeds_baseline',
        impact: 'moderate',
        localRule: 'When construction in fill is required, both the primary area and the expansion area must be prepared',
        stateBaseline: 'Reserve area must be identified but not necessarily prepared at time of initial construction',
        gap: 'Doubles the fill preparation work and cost at initial construction',
        localRegulation: 'Section V',
        stateCitation: '310 CMR 15.255',
        details: "Title 5 requires identification of a reserve area but does not mandate its full preparation at the time of initial system construction. Sudbury requires both the primary and expansion areas to be fully prepared in fill, increasing upfront earthwork, material, and grading costs. For ADU projects that require fill construction — common in areas with shallow groundwater or slow-percolating soils — this effectively doubles the site preparation scope.",
      },
      {
        id: 'SUD-T5-07',
        title: 'Bedroom Reallocation Policy',
        status: 'needs_review',
        impact: 'critical',
        localRule: "Not addressed in the Rules & Regulations Governing the Subsurface Disposal of Sewage. Sudbury's regulations require that daily sewage design flow be based on the number of rooms usable as bedrooms (Section IV), but do not specifically address reallocation between a principal dwelling and an ADU.",
        stateBaseline: "Title 5 (310 CMR 15.000) calculates septic capacity based on total bedroom count on a lot. No state-level provision specifically addresses bedroom reallocation between a principal dwelling and an ADU.",
        gap: 'No explicit local policy — standard practice emerging statewide but not codified in Sudbury',
        localRegulation: 'No specific regulation identified',
        stateCitation: '310 CMR 15.002 (bedroom definition), 310 CMR 15.203 (design flow)',
        details: "Bedroom reallocation has particular significance in Sudbury given the prohibition on sewage pumps (SUD-T5-03) and leaching beds (SUD-T5-02), which limit design flexibility for expanded systems. If reallocation avoids a net flow increase, the ADU addition may not require system expansion — bypassing the pump prohibition and fill construction requirements entirely. However, Sudbury's strict variance standard (Section XVI — neither financial hardship nor past practices are adequate grounds) suggests the BOH may scrutinize any approach that appears to circumvent design requirements. Direct inquiry to the Sudbury Board of Health is recommended.",
        sourcingNote: "This provision is based on cross-town pattern analysis and builder interviews, not Sudbury-specific BOH documentation. Verification with Sudbury's BOH is recommended before relying on this pathway.",
      },
    ],
    sources: [
      { label: 'Sudbury Board of Health — Rules & Regulations, Subsurface Disposal of Sewage', url: 'https://sudbury.ma.us/health/regulations-subsurface-disposal-of-sewage-2/' },
      { label: 'Sudbury Board of Health — In-Ground Irrigation Systems Regulations (Article XXVII)', url: 'https://sudbury.ma.us/boardofhealth/?attachment_id=182' },
      { label: 'Sudbury Health Department', url: 'https://sudbury.ma.us/health/' },
      { label: '310 CMR 15.211 — Minimum Setback Distances', url: 'https://www.law.cornell.edu/regulations/massachusetts/310-CMR-15-211' },
      { label: '310 CMR 15.212 — Depth to Groundwater', url: 'https://www.law.cornell.edu/regulations/massachusetts/310-CMR-15-212' },
    ],
  },
  {
    slug: 'southborough',
    name: 'Southborough',
    county: 'Worcester County',
    regulatoryLayer: 'Modifications to Massachusetts Title 5 Code (approved March 28, 2000; amended March 11, 2004 and June 30, 2014)',
    stateBaseline: '310 CMR 15.000 (Title 5 of the State Environmental Code)',
    localAuthority: 'M.G.L. c. 111, § 31',
    lastReviewed: '2026-03-08',
    bottomLine: "Southborough's Title 5 modifications reflect the town's location within the Sudbury Reservoir watershed and its extensive glacial till soils. Septic tank capacity must be 200% of design flow with a minimum of 1,500 gallons — double the Title 5 standard. All outlet tees require an effluent filter with a maximum 1/8-inch orifice. In areas with bedrock outcrops or shallow-to-bedrock soils, a minimum of 4 feet of naturally occurring pervious soil must extend 10 feet outside the soil absorption system in all directions — a site suitability standard well beyond Title 5. For new construction in slow-percolating soils (31–60 min/inch), trenches must have a minimum 9-foot sidewall separation to qualify the between-trench area as reserve space. Septic system installations are banned from December through March. Mandatory septic tank pumping is required at every Title 5 inspection. Domestic garbage grinders are prohibited outright. These provisions create a materially more demanding design and construction environment for ADU septic systems.",
    provisions: [
      {
        id: 'SBO-T5-01',
        title: 'Septic Tank Capacity',
        status: 'exceeds_baseline',
        impact: 'high',
        localRule: '200% of design flow or 48-hour hydraulic detention, whichever is greater. Minimum 1,500 gallons.',
        stateBaseline: 'Minimum capacity based on design flow per 310 CMR 15.223; typically 1,000–1,500 gallons for residential',
        gap: '2× the state design flow capacity requirement',
        localRegulation: '15.223 (local modification)',
        stateCitation: '310 CMR 15.223',
        details: "A 1-bedroom ADU at 110 gpd design flow would require a septic tank with 220 gallons of effective liquid capacity under Title 5 — but Southborough's 200% rule and 1,500-gallon minimum means the tank must be at least 1,500 gallons regardless. For combined systems serving a main house and ADU, the tank capacity calculation doubles the total design flow. This increases both the physical footprint and cost of the tank installation.",
      },
      {
        id: 'SBO-T5-02',
        title: 'Outlet Filter Requirement',
        status: 'exceeds_baseline',
        impact: 'moderate',
        localRule: 'All outlet tees fitted with an outlet filter (Zabel, Orenco, Polylock, Infiltrator, or equal) with maximum 1/8" orifice',
        stateBaseline: 'Outlet tee required; effluent filter not universally mandated under Title 5',
        gap: 'Mandatory effluent filtration on all systems',
        localRegulation: '15.227(7) (local modification)',
        stateCitation: '310 CMR 15.227',
        details: "The outlet filter requirement adds a maintenance obligation — filters must be cleaned periodically to prevent backup — but also provides early warning of tank pumping needs. The Board's stated rationale is protecting the Sudbury Reservoir watershed by ensuring more refined effluent reaches the soil absorption system. This is a cost and maintenance add, not a design constraint, but applies to all new systems including ADU-related installations.",
      },
      {
        id: 'SBO-T5-03',
        title: 'Pervious Soil Requirement',
        status: 'exceeds_baseline',
        impact: 'high',
        localRule: '4 ft of naturally occurring pervious soils required, extending 10 ft outside SAS in all directions, in areas with exposed bedrock outcrops or shallow-to-bedrock soils',
        stateBaseline: 'Soil suitability evaluated within the SAS footprint per 310 CMR 15.240–15.255',
        gap: 'Soil suitability zone extends 10 ft beyond SAS boundary; naturally occurring soil required (no fill)',
        localRegulation: 'Percolation Testing (2004 modification)',
        stateCitation: '310 CMR 15.240',
        details: "This provision requires that the Board be satisfied that pervious soils exist not just within the soil absorption system but extending 10 feet outside it in all directions. In bedrock areas — common in Southborough's glacial till terrain — this can disqualify locations that would pass standard Title 5 testing within the SAS footprint. The requirement for naturally occurring soil means fill cannot substitute, further limiting options on lots with shallow bedrock.",
      },
      {
        id: 'SBO-T5-04',
        title: 'Trench Separation',
        status: 'exceeds_baseline',
        impact: 'moderate',
        localRule: '9 ft minimum separation between excavation sidewalls of primary trenches for new construction in soils with percolation rates 31–60 min/inch',
        stateBaseline: 'Standard trench separation per 310 CMR 15.242 (typically 4–6 ft)',
        gap: '+3 to +5 ft above standard separation in slow-perc soils',
        localRegulation: 'Trenches (2004 modification)',
        stateCitation: '310 CMR 15.242',
        details: "In slow-percolating soils, the 9-foot trench separation increases the total footprint of the leaching field. The between-trench area can serve as system reserve only if this separation is achieved. On lots where the available leaching area is limited by setbacks, topography, or lot size, the wider separation may reduce the number of trenches that can fit, potentially limiting design flow capacity for ADU additions.",
      },
      {
        id: 'SBO-T5-05',
        title: 'Winter Installation Ban',
        status: 'exceeds_baseline',
        impact: 'moderate',
        localRule: 'No septic system installations during December, January, February, and March. Case-by-case exceptions with BOH or Director of Public Health approval.',
        stateBaseline: 'No seasonal installation restriction under Title 5',
        gap: '4-month construction blackout (1 month longer than Weston)',
        localRegulation: 'Septic Installation Restrictions',
        stateCitation: '310 CMR 15.000',
        details: "Southborough's winter ban is four months — December through March — one month longer than Weston's three-month ban. ADU projects requiring new septic construction or expansion cannot proceed with site work during this period. The exception pathway requires case-by-case BOH approval, and new ADU construction would likely not qualify unless posing a health concern.",
      },
      {
        id: 'SBO-T5-06',
        title: 'Mandatory Pumping at Inspection',
        status: 'exceeds_baseline',
        impact: 'moderate',
        localRule: 'Mandatory septic tank and pump chamber pumping at time of every 310 CMR 15.301 system inspection, unless pumped within prior 6 months',
        stateBaseline: 'Inspection does not require simultaneous pumping under Title 5',
        gap: 'Adds pumping cost to every Title 5 inspection event',
        localRegulation: 'Mandatory Septic Tank Pumping (2014 modification)',
        stateCitation: '310 CMR 15.301–15.302',
        details: "This adds approximately $300–$500 per inspection event. For ADU projects, the Title 5 inspection required before system modification or expansion will trigger mandatory pumping. The provision also means that any future property transfer inspection — standard in Massachusetts real estate transactions — includes mandatory pumping. This is an ongoing operational cost, not a design constraint.",
      },
      {
        id: 'SBO-T5-07',
        title: 'Garbage Grinders Prohibited',
        status: 'exceeds_baseline',
        impact: 'moderate',
        localRule: 'Domestic garbage grinders are prohibited',
        stateBaseline: 'Garbage grinders permitted under Title 5; design flow adjustment may apply',
        gap: 'Complete prohibition (vs. Weston, which permits but requires 150% leaching area)',
        localRegulation: '15.223(3) (local modification)',
        stateCitation: '310 CMR 15.223',
        details: "Southborough takes a stricter approach than Weston: rather than accommodating garbage grinders through oversized leaching areas, it prohibits them outright. For ADU design, this simplifies the leaching area calculation — no 150% multiplier — but means ADU kitchens cannot include garbage disposals. This is a use restriction, not a design constraint, but must be communicated to ADU builders and future occupants.",
      },
      {
        id: 'SBO-T5-08',
        title: 'Bedroom Reallocation Policy',
        status: 'needs_review',
        impact: 'critical',
        localRule: "Not addressed in the Title 5 Code Addendum. Southborough's modifications focus on tank sizing, soil suitability, and construction standards rather than bedroom counting or flow allocation.",
        stateBaseline: "Title 5 (310 CMR 15.000) calculates septic capacity based on total bedroom count on a lot. No state-level provision specifically addresses bedroom reallocation between a principal dwelling and an ADU.",
        gap: 'No explicit local policy — standard practice emerging statewide but not codified in Southborough',
        localRegulation: 'No specific regulation identified',
        stateCitation: '310 CMR 15.002 (bedroom definition), 310 CMR 15.203 (design flow)',
        details: "Bedroom reallocation in Southborough has particular significance because the 200% tank capacity requirement (SBO-T5-01) scales with design flow. If reallocation avoids a net flow increase, the existing tank may already meet the capacity requirement, avoiding a costly tank upgrade. However, the mandatory pumping and inspection requirements (SBO-T5-06) mean any system modification will trigger a full inspection with pumping. The pervious soil requirement (SBO-T5-03) could block system expansion on bedrock lots, making reallocation the only viable pathway. Direct inquiry to the Southborough Board of Health is recommended.",
        sourcingNote: "This provision is based on cross-town pattern analysis and builder interviews, not Southborough-specific BOH documentation. Verification with Southborough's BOH is recommended before relying on this pathway.",
      },
    ],
    sources: [
      { label: 'Southborough Board of Health — Title 5 Code Modifications (2000, 2004, 2014)', url: 'https://www.southboroughma.gov/321/Health-Department' },
      { label: 'Southborough Board of Health — Septic Installation Restrictions', url: 'https://www.southboroughma.gov/321/Health-Department' },
      { label: '310 CMR 15.211 — Minimum Setback Distances', url: 'https://www.law.cornell.edu/regulations/massachusetts/310-CMR-15-211' },
      { label: '310 CMR 15.223 — Septic Tank Standards', url: 'https://www.law.cornell.edu/regulations/massachusetts/310-CMR-15-223' },
    ],
  },
];
