// Auto-generated by scripts/fetch-potw-data.ts — run once to populate
export interface POTWRecord {
  name: string
  designFlowMGD: number | null
  actualFlowMGD: number | null
  permitStatus: string | null
  city: string | null
}

export const MA_POTW_LOOKUP: Record<string, POTWRecord> = {}
